---

# Volume Replicator Docker-Compose file.
#
# Environment variables: -
#
# - IMAGE_TAG The replicator image version tag
#             (default latest)
#
# i.e.: -
#
#   IMAGE_TAG=stable docker-compose build
#   IMAGE_TAG=stable docker-compose push

version: '3.8'

services:

  volume-replicator:
    build:
      context: .
    image: informaticsmatters/volume-replicator:${IMAGE_TAG:-latest}
    container_name: volume-replicator
